name: Notebook Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.8

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to version 3

    - name: Set up Python
      uses: actions/setup-python@v3  # Updated to use the latest version
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pip install jupyter nbconvert  
        pip install -U scikit-learn
        pip install scikit-plot
        
    - name: Run tests
      run: |
        jupyter nbconvert --execute --inplace Jenny_INNHotels_FullCode.ipynb
